"""add_qc_review_checklist_status

Revision ID: 0bc41e47fb42
Revises: a1b2c3d4e5f6
Create Date: 2026-05-28 21:20:56.198386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0bc41e47fb42'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('qc_review_checklist_statuses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('review_id', sa.UUID(), nullable=False),
    sa.Column('checklist_item_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['checklist_item_id'], ['checklist_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['review_id'], ['qc_reviews.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_qc_review_checklist_statuses_checklist_item_id'), 'qc_review_checklist_statuses', ['checklist_item_id'], unique=False)
    op.create_index(op.f('ix_qc_review_checklist_statuses_review_id'), 'qc_review_checklist_statuses', ['review_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_qc_review_checklist_statuses_review_id'), table_name='qc_review_checklist_statuses')
    op.drop_index(op.f('ix_qc_review_checklist_statuses_checklist_item_id'), table_name='qc_review_checklist_statuses')
    op.drop_table('qc_review_checklist_statuses')
    # ### end Alembic commands ###
