"""Add system_config

Revision ID: 93db5642dc2d
Revises: 25b5240270cd
Create Date: 2026-06-26 08:15:19.860775

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '93db5642dc2d'
down_revision: Union[str, None] = '25b5240270cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_anchor_resolutions_anchor_id', table_name='anchor_resolutions')
    op.drop_index('ix_anchor_resolutions_success', table_name='anchor_resolutions')
    op.drop_table('anchor_resolutions')
    op.drop_index('ix_finding_anchors_finding_id', table_name='finding_anchors')
    op.drop_index('ix_finding_anchors_type', table_name='finding_anchors')
    op.drop_table('finding_anchors')
    op.drop_index('ix_document_anchor_cache_document', table_name='document_anchor_cache')
    op.drop_index('ix_document_anchor_cache_key', table_name='document_anchor_cache')
    op.drop_index('ix_document_anchor_cache_valid', table_name='document_anchor_cache')
    op.drop_table('document_anchor_cache')
    op.drop_index('ix_documents_sharepoint_ids', table_name='documents')
    op.drop_index('ix_documents_storage_type', table_name='documents')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_documents_storage_type', 'documents', ['storage_type'], unique=False)
    op.create_index('ix_documents_sharepoint_ids', 'documents', ['sharepoint_site_id', 'sharepoint_item_id'], unique=False)
    op.create_table('document_anchor_cache',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('document_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('cache_key', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('resolved_position', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('last_accessed', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('access_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('is_valid', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name='document_anchor_cache_document_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='document_anchor_cache_pkey')
    )
    op.create_index('ix_document_anchor_cache_valid', 'document_anchor_cache', ['is_valid', 'expires_at'], unique=False)
    op.create_index('ix_document_anchor_cache_key', 'document_anchor_cache', ['cache_key'], unique=False)
    op.create_index('ix_document_anchor_cache_document', 'document_anchor_cache', ['document_id'], unique=False)
    op.create_table('finding_anchors',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('finding_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('anchor_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('primary_anchor_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('fallback_anchors', postgresql.JSON(astext_type=sa.Text()), server_default=sa.text("'[]'::json"), autoincrement=False, nullable=True),
    sa.Column('confidence_score', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text("'1'::double precision"), autoincrement=False, nullable=False),
    sa.Column('editor_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('resolution_history', postgresql.JSON(astext_type=sa.Text()), server_default=sa.text("'[]'::json"), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['finding_id'], ['qc_findings.id'], name='finding_anchors_finding_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='finding_anchors_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_finding_anchors_type', 'finding_anchors', ['anchor_type', 'editor_type'], unique=False)
    op.create_index('ix_finding_anchors_finding_id', 'finding_anchors', ['finding_id'], unique=False)
    op.create_table('anchor_resolutions',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('anchor_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('resolved_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('resolution_method', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('resolution_time_ms', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('success', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('error_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('editor_context', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('document_version', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['anchor_id'], ['finding_anchors.id'], name='anchor_resolutions_anchor_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='anchor_resolutions_pkey')
    )
    op.create_index('ix_anchor_resolutions_success', 'anchor_resolutions', ['success', 'resolved_at'], unique=False)
    op.create_index('ix_anchor_resolutions_anchor_id', 'anchor_resolutions', ['anchor_id'], unique=False)
    # ### end Alembic commands ###
